### ISSUE TITLE
unexpected token u in JSON

### ISSUE THREAD

**Issue by vnehess** [keirbowden/BBLDS#1]
steps to repro

install unmanaged package
load BBLeadBoard page

expected cool kanban board

observed:  page fails to load
console error : 
```
VM2410:2 Uncaught SyntaxError: Unexpected token u in JSON at position 7060
    at JSON.parse (<anonymous>)
    at XMLHttpRequest.xhr.onreadystatechange (lightning.out.delegate.js?v=1492717718095:113)
```﻿

**Comment by vnehess** [comment]
perhaps i missed some setup steps?
mydomain is enabled
LockerService is enabled

thanks

**Comment by keirbowden** [comment]
Hi Ron - good to hear from you. This was down to mismatched attribute names and is fixed in the latest version of the unmanaged package : 	https://login.salesforce.com/packaging/installPackage.apexp?p0=04t24000000AqHA

I also found an issue around installing into an org with a package namespace, which I've detailed in the updated readme : https://github.com/keirbowden/BBLDS/blob/master/README.md

Let me know if you have any further issues.

**Comment by vnehess** [comment]
thanks!
